# Generated by Django 4.0 on 2022-11-10 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('cnpj', models.CharField(max_length=11)),
                ('logradouro', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=80)),
                ('fone', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('cnpj', models.CharField(max_length=11)),
                ('logradouro', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=80)),
                ('fone', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('barras', models.CharField(max_length=11, null=True)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('Especie', 'Especie'), ('Cartão Crédito', 'Cartão Crédito'), ('Cartão Débito', 'Cartão Débito')], max_length=80)),
                ('valor_total', models.FloatField()),
                ('valor_pago', models.FloatField()),
                ('troco', models.FloatField()),
                ('cliente', models.ForeignKey(max_length=80, on_delete=django.db.models.deletion.CASCADE, to='webform.cliente')),
            ],
        ),
    ]
